### ISSUE TITLE
Verify hard-neg mining notebook works with large unlabeled sets.

### ISSUE THREAD

**Issue by PatrickBue** [microsoft/ComputerVision#153]
Try notebook with negative (aka unlabeled) dataset of e.g. 20k images.

**Comment by jiata** [comment]
@loomlike has this been tested?

**Comment by PatrickBue** [comment]
No it has not been tested using a large dataset of >10,000 images. I will do that when I implement this for the OD scenario.

**Comment by PatrickBue** [comment]
Tested with 7,000 negative images and it's working wonderfully.
